service: covid19-data
frameworkVersion: '2'

custom:
  region: ap-southeast-1
  project: covid-19
  bucket: "data.covid-19.drunkard-pig.com"

provider:
  name: aws
  region: ${opt:region, self:custom.region}
  runtime: nodejs12.x
  stackName: ${self:service}-stack
  stackTags: # Optional CF stack tags
    project: ${self:custom.project}
  lambdaHashingVersion: "20201221"
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - s3:GetObject
          - s3:GetObjectAcl
          - s3:PutObject
          - s3:PutObjectAcl
          - s3:DeleteObject
        Resource: "arn:aws:s3:::${self:custom.bucket}/*"
      - Effect: Allow
        Action:
          - s3:ListBucket
        Resource: "arn:aws:s3:::${self:custom.bucket}"

functions:
  import-covid-19-data:
    handler: import-data/import-data-handler.importCovid19Data
    events:
      # every 15 minutes
      - schedule: cron(0/15 * * * ? *)
    environment:
      DATA_URL: "https://covid19.who.int/page-data/table/page-data.json"
      BUCKET: ${self:custom.bucket}
      MAX_FILES_ALLOWED: 2

resources:
  # AWS CloudFormation Template
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
